# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1430cfdea87a339525bd34a572e148eee5ea07a17ca5150d54ad7bc61386dacfdeed46e46f3dc1c25999e872b2581842bae145a44c1653c040896ee4a390da7

test:
  secret_key_base: 8fc98387efd6fab414331b4f28b5a8654e11c6354f56f8110668227f808b6636c5efa0342e51027e7b5a18179f35dfdaaefa6d4ca8bc1e52c105515ed4251d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
